language: python
sudo: false
cache: pip

install:
  - pip install -e .
  - pip install -U flake8 pytest

script:
  - flake8 --ignore=W,E203,F405 --max-line-length=88
  - pytest

jobs:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "3.5"
    - python: "2.7"

notifications:
  email: false
