name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Linting
        run: |
          pip install flake8
          flake8 --ignore=W,E203,F405 --max-line-length=88 cfonts tests
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pdm install -d
      - name: Run Tests
        run: |
          pdm run pytest tests
