name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: "x64"
      - name: Install build tool
        run: |
          pip install -U build
      - name: Build artifacts
        run: |
          python -m build
      - name: Test Build
        run: |
          pip install twine
          twine check dist/*
      - name: Upload to Pypi
        run: |
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
